#server.port:8088
#jwt.secret=javainuse
#jwt.get.token.uri=/authenticate
#
#
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#https://betterprogramming.pub/how-to-monitor-a-spring-boot-app-with-prometheus-and-grafana-22e2338f97fc
#http://host.docker.internal:9090 //give this in docker- grafana local server name.will not work with localhost:9090


 
jwt:
  get:
    token:
      uri: /authenticate
  secret: javainuse
  
server:
  port: '8088'
  
spring:
  data:
    mongodb:
      port: '27017'
      host: localhost
  application:
    name: My Spring Boot Application
         
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true      
      
      
      
 